### ISSUE TITLE
HideUtils could not be compiled.

### ISSUE THREAD

**Issue by kep1122** [Arashiryuu/crap#201] opened 2023-02-03 12:24 UTC
TypeError: Cannot destructure property 'openModal' of 'WebpackModules.getByProps(...)' as it is undefined.
    at buildPlugin (betterdiscord://plugins/HideUtils.plugin.js:119:11)
    at eval (betterdiscord://plugins/HideUtils.plugin.js:1547:5)
    at eval (betterdiscord://plugins/HideUtils.plugin.js:1548:3)
    at Object.requireAddon (<anonymous>:4:37112)
    at Object.loadAddon (<anonymous>:4:8234)
    at Object.loadAddon (<anonymous>:4:34784)
    at Object.loadAllAddons (<anonymous>:4:10708)
    at Object.initialize (<anonymous>:4:5130)
    at Object.initialize (<anonymous>:4:33979)
    at Object.startup (<anonymous>:4:390667)

**Comment by Arashiryuu** [comment] 2023-02-03 12:25
duplicate of #195.

**Closed by Arashiryuu** 2023-02-03 12:25 UTC
Labels: bug
